language: c
before_script:
  - hg clone 'http://hg.linux-ha.org/%7Cexperimental/assimilation/'
script:
  - mkdir a
  - cd a
  - pwd
  - cmake ../assimilation
  - sudo apt-get install doxygen
  - cpack
