language: c

before_install:
  - uname -a
  - cat /etc/issue
  - env
  - sudo cat /var/log/syslog
  - sudo cat /var/log/auth.log
#  - sudo apt-get update -qq
#  - sudo apt-get install -qq doxygen valgrind libpcap-dev

#before_script:
#  - hg clone 'http://hg.linux-ha.org/%7Cexperimental/assimilation/'
#  - sudo pip install testify ctypesgen py2neo==1.4.5 tornado
#  - pip freeze
#  - dpkg-query --show

#services:
#  - neo4j

#script:
#  - mkdir root_of_binary_tree
#  - cd root_of_binary_tree
#  - pwd
#  - cmake ../assimilation
#  - cpack

#run some tests
#  - netstat -a
#  - cd testcode
#  - ifconfig
#  - sudo apt-get install strace
#  - wget https://raw.github.com/borgified/diffdpkg/master/grind.sh
#  - mv ./grind.sh ../../assimilation/testcode/.
#  - chmod a+x ../../assimilation/testcode/grind.sh
#  - sudo ../../assimilation/testcode/grind.sh
#  - cd ../../assimilation/cma
#  - testify tests
#  - ../../root_of_binary_tree/testcode/pinger ::1


