language: c

before_install:
# - echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
 - sudo apt-get -y update && apt-get -y install --no-install-recommends gcc cmake make pkg-config libglib2.0-dev resource-agents wget libpcap0.8-dev rsyslog 
 - sudo apt-get -y install --no-install-recommends python-pip python-flask debianutils lsof python-netaddr valgrind python-dev lsb-release python-demjson
 - sudo apt-get -y install --no-install-recommends bind9 host           # So we have some services to monitor in system testing
 - sudo apt-get -y install --no-install-recommends strace gdb tcpdump   # For debugging...
 - sudo pip install ctypesgen 'py2neo<2.0' getent
 - pwd

#libsodium
# - cd /root && mkdir -p assimilation/bin/buildtools assimilation/bin/libsodium assimilation/packages
# - wget http://hg.linux-ha.org/assimilation/raw-file/tip/buildtools/libsodium.mkdeb.sh -O /root/assimilation/bin/buildtools/libsodium.mkdeb.sh
# - cd /root/assimilation/bin/libsodium && bash ../buildtools/libsodium.mkdeb.sh && dpkg --install *.deb && cp *.deb /root/assimilation/packages

services:
  - neo4j

install:

script:

