language: c

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq doxygen valgrind libpcap-dev

before_script:
  - hg clone 'http://hg.linux-ha.org/%7Cexperimental/assimilation/'
  - sudo pip install testify ctypesgen py2neo tornado

script:
  - mkdir root_of_binary_tree
  - cd root_of_binary_tree
  - pwd
  - cmake ../assimilation
  - cpack

#run some tests

  - cd testcode
  - ../../assimilation/testcode/grind.sh
  - cd ../../assimilation/cma
  - testify tests
  - ../../root_of_binary_tree/testcode/pinger ::1

services:
  - neo4j
